# Generated by Django 5.2 on 2025-06-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resume_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='language',
            field=models.TextField(),
        ),
    ]
