# Generated by Django 5.2 on 2025-06-14 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
