# Generated by Django 5.2 on 2025-06-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_comment_id_alter_customuser_id_alter_news_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='picture',
            field=models.ImageField(blank=True, help_text='Upload a picture for the news article.', null=True, upload_to='pictures/'),
        ),
    ]
