# Generated by Django 5.2 on 2025-07-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_news_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='content',
            new_name='meta',
        ),
        migrations.AddField(
            model_name='resume',
            name='add_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_exp',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ResumeSection',
        ),
    ]
