# Generated by Django 5.2 on 2025-07-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_content_resume_meta_resume_add_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='user_picture',
            field=models.ImageField(blank=True, help_text='Upload a picture for the news article.', null=True, upload_to='user-pictures/'),
        ),
    ]
